### PR TITLE
HearthPwn card tooltips

### PR DESCRIPTION
**Pull request by Leonix**
Hey Freezard, thanks for an awesome tool!

This PL adds convenient [card tooltips by HearthPwn](http://www.hearthpwn.com/tooltips). Preview here: http://leonix.github.io/hs-collection-tracker/

Unfortunately, this creates a liability to update local card database with cards ID as used by HearthPwn. I have found no way to avoid that. I myself grabbed data from [Hearthstone Linkifier](https://chrome.google.com/webstore/detail/hearthstone-linkifier/hgfciolhdhbagnccplcficnahgleflam) chrome extension. Kudos for the author.

### CODE REVIEW

**Comment by Freezard** [comment]
Hi and thanks for the feature! I've been thinking of adding this, but seems I forgot making it an issue.

Do you have any idea if the HearthPwn card IDs are the same as the card IDs from the game? In that case I can just add the IDs to the collection card data.

If you know a way to add a delay when hovering over the cards until the tooltips show up (like a 1 second delay), I think it would be less messy since you're kinda hovering over cards all the time.

And one problem: The tooltips stop working when you switch tab to ie progress and then back to the tracker, the site uses templates so you'd have to add the data-tooltip-hrefs each time the tracker template is switched to. But I can probably fix that myself.

**Comment by Leonix** [comment]
I don't think HearthPwn and in-game ids match. At least I see no similarities between `all-collectibles.json` and `card-ids.json`.

There's no imidiately available way to configure the tooltip script, at least no delay option. But I'm pretty sure it's possible with some monkey-patching. I'll look into that. (One second is way too much I think, though.)

And I'll fix bug with switching to a different tab, too.

**Comment by Leonix** [comment]
Delays and switching between tabs [should work](http://leonix.github.io/hs-collection-tracker/) now.

**Comment by Freezard** [comment]
Awesome thanks a lot, will commit soon.

**Comment by Freezard** [comment]
Unfortunately I had to comment it out for now, it doesn't work on IE and on
both IE and Edge it slows down the site so much when clicking around on
cards/class tabs that it stops responding. Works fine on Chrome, haven't
tested Firefox. You have any idea why this is?

**Pull request merged**
