### PR TITLE
fixed import from hearthpwn

### PR DESCRIPTION
**Pull request by dluk**

### CODE REVIEW

**Comment by Freezard** [comment]
Hi, thanks for fixing this :) I was actually about to move the site to Heroku with a similar fix.

Can you explain a bit how it works? Is it a way of running nodejs in the web browser?

**Comment by dluk** [comment]
Hi, I used a npm package `cheerio` to query html with jquery/css like syntax. It wouldn't work in a browser so it had to be bundled so I used `webpack` for that. It basically scans imported modules and bundles it together with your app's js. When you change something in the code, you have to run npm script `npm run build`. To run it locally `npm run serve`. Before all of that you need to install node of course and run `npm install` to download the dependencies (dependencies and scripts are in package.json). Recommended IDE - Visual Studio Code.

**Comment by dluk** [comment]
Also I found some bugs:
1. For some reason when importing it fails to recognize one card `Mosh'ogg Enforcer`. No idea why, but I added a null check and log to console so it won't throw an exception.
2. It won't gracefully handle the case when collection is private in HearthPwn. Need to add some check and display a message to the user.
3. If you import multiple times from HearthPwn - it adds the same cards twice (or as many times as you import). You have to clear browser data (local storage) before you import each time. Maybe we need to add a checkbox in the username screen which would say "fresh import" and if checked it will clear the cards before importing.

**Comment by Freezard** [comment]
It worked last time I tested it, but now I'm getting CORS issues with the GitHub version.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cors-anywhere.herokuapp.com/http://www.hearthpwn.com/members/Freezard/collection. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by dluk** [comment]
You mean locally?

**Comment by Freezard** [comment]
Both locally and online. But now it works again, so I've no idea what's going on.

I fixed 2 & 3. About 1, can't find any error here so maybe HearthPwn wrote the wrong id in the collection. Can check later, not a big deal for now.

**Pull request merged**
